### ISSUE TITLE
Keeps running clean

### ISSUE THREAD

**Issue by rwoodruff** [dogeth/ccnet.git.plugin#1]
Hello, 

The plugin keeps running a clean over my working directory which is deleting all my files. Is there any way to prevent this?

Thanks.

-- Rodney

**Comment by dogeth** [comment]
This is actually by design.  Before a build starts, I want the working directory to be in a known "clean" state (no artifacts left over from a previous build).  Part of our build process is to copy the build output to a "deployment" location, so there is no problem for us to clear out the working directory.

You are welcome to fork the code and add an option to skip the clean, send me a note when you are done and I'll merge in your changes if you like.
